### ISSUE TITLE
Should we merge the `open-all` branch?

### ISSUE THREAD

**Issue by pegeler** [SpectrumHealthResearch/MethylMallet#6]
The `open-all` branch uses a different approach. Instead of appending data one column at a time, it opens all files simultaneously. On small datasets (~4 files), it is actually much slower. However, I think it will scale more gracefully when we start reading in datasets into the hundreds or thousands. It'd like to run some tests on the datasets of various sizes to find the break-even point.

That said, the number of files in this dataset is already pushing up against the soft limit of the number of files that can be opened at one time.

Another thing to consider is using this approach but opening and seeking each file as needed. The code to do so is written but commented out. Sounds too slow, though I haven't tried it.

**Comment by pegeler** [comment]
Update: 3303a78ed7d9babb41bebaff92207a5a4049a44f raises exception if too many files are given. An alternative could be falling back to the open-files-as-needed approach.

**Comment by brenkiz** [comment]
I would wait to merge until running more trials to find out if the increase in speed is worth the issue with larger datasets.  If it turns out to be worth it, maybe with too-large datasets the program continues with the open-files-as-needed approach?  Not sure if that's helpful input at all but that's my current take on it.

**Comment by nullderp** [comment]
So, there's some tomfoolery one could use to increase the maximum open files, but it is a hazard given that it takes configuration, and could be catastrophic if the power went off or something. I would not advise using this approach, usability and reliability are more important here.

**Comment by pegeler** [comment]
You're right. The way to get this approach to work is to write out a bunch of temp files and then gather them. I'll write some code against that tonight.
